from .aluno_permission import AlunoPermission, IsAluno, GetPermission
from .coordenador_full_permission import CoordenadorFullPermission
from .funcionario_permission import FuncionarioPermission
from .professor_create_update_permission import ProfessorCreateUpdatePermission
from .professor_update_permission import ProfessorUpdatePermission
from .diretor_escola_permission import DiretorEscolaPermission
