# Generated by Django 4.2.7 on 2023-12-18 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_remove_email_escola_remove_telefone_escola_and_more'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPessoa',
            fields=[
                ('email_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='escolas.email')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_emails', to='pessoas.pessoa')),
            ],
            options={
                'verbose_name': 'e-mail',
            },
            bases=('escolas.email',),
        ),
        migrations.CreateModel(
            name='TelefonePessoa',
            fields=[
                ('telefone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='escolas.telefone')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_telefones', to='pessoas.pessoa')),
            ],
            options={
                'verbose_name': 'telefone',
            },
            bases=('escolas.telefone',),
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Telefone',
        ),
    ]
