# Generated by Django 4.2.7 on 2024-02-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_agendarecados_recado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendarecados',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_agendas', to='pessoas.aluno'),
        ),
    ]
