# Generated by Django 4.2.7 on 2023-12-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_responsavel_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='descricao_pcd',
            field=models.TextField(blank=True, null=True, verbose_name='descrição da pcd'),
        ),
    ]
