# Generated by Django 4.2.7 on 2023-12-18 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_remove_email_escola_remove_telefone_escola_and_more'),
        ('pessoas', '0002_emailpessoa_telefonepessoa_remove_telefone_pessoa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporte',
            name='telefone',
        ),
        migrations.CreateModel(
            name='TelefoneTransporte',
            fields=[
                ('telefone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='escolas.telefone')),
                ('transporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transporte_telefones', to='pessoas.transporte')),
            ],
            options={
                'verbose_name': 'telefone',
            },
            bases=('escolas.telefone',),
        ),
    ]
