# Generated by Django 4.2.7 on 2024-02-07 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_alter_avisoescola_options_alter_muralavisos_options_and_more'),
        ('pessoas', '0003_alter_agendarecados_aluno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'funcionário', 'verbose_name_plural': 'funcionários'},
        ),
        migrations.AddField(
            model_name='aluno',
            name='retrato',
            field=models.ImageField(blank=True, default='', null=True, upload_to='alunos_retratos/'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='atualizada_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dialetivo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dialetivo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='retrato',
            field=models.ImageField(blank=True, default='', null=True, upload_to='funcionarios_retratos/'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recado',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transporte',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transporte',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='escola',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='escola',
            field=models.ManyToManyField(related_name='escola_pessoas', to='escolas.escola'),
        ),
    ]
