# Generated by Django 4.2.7 on 2023-12-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_remove_transporte_telefone_telefonetransporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporte',
            name='itinerario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='nomeAuxiliar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='nomeMotorista',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
