# Generated by Django 4.2.7 on 2023-12-30 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_alter_aluno_descricao_pcd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailpessoa',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_emails', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='telefonepessoa',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_telefones', to='pessoas.pessoa'),
        ),
    ]
