# Generated by Django 4.2.7 on 2024-02-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0004_alter_sala_quantidade_alunos'),
        ('pessoas', '0005_rename_computada_avaliacao_finalizada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='escolas',
            field=models.ManyToManyField(blank=True, related_name='escola_pessoas', to='escolas.escola'),
        ),
    ]
