# Generated by Django 4.2.7 on 2024-02-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0004_alter_sala_quantidade_alunos'),
        ('pessoas', '0006_alter_pessoa_escolas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='escolas',
            field=models.ManyToManyField(related_name='escola_pessoas', to='escolas.escola'),
        ),
    ]
