# Generated by Django 4.2.7 on 2023-12-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0008_alter_telefonetransporte_transporte'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dialetivo',
            unique_together={('data', 'frequencia')},
        ),
    ]
