# Generated by Django 4.2.7 on 2024-02-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0008_rename_finalizada_avaliacao_confirmar'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='finalizar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='situacao_materia',
            field=models.CharField(blank=True, choices=[('A', 'Aprovado'), ('R', 'Reprovado')], max_length=10, null=True),
        ),
    ]
