# Generated by Django 4.2.7 on 2024-02-10 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0009_media_finalizar_media_situacao_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='finalizar',
        ),
        migrations.RemoveField(
            model_name='media',
            name='situacao_materia',
        ),
    ]
