# Generated by Django 4.2.7 on 2024-02-10 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0005_alter_sala_numero_alter_sala_unique_together'),
        ('pessoas', '0010_remove_media_finalizar_remove_media_situacao_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(blank=True, choices=[('A', 'Aprovado'), ('R', 'Reprovado')], max_length=10, null=True)),
                ('finalizar', models.BooleanField(default=False)),
                ('boletim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletim_situacoes', to='pessoas.boletim')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_situacoes', to='escolas.disciplina')),
            ],
        ),
    ]
