# Generated by Django 4.2.7 on 2024-01-08 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0010_avaliacao_computada_alter_avaliacao_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='turma',
            new_name='turmas',
        ),
    ]
