# Generated by Django 4.2.7 on 2024-02-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0011_situacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situacao',
            options={'verbose_name': 'situação', 'verbose_name_plural': 'situações'},
        ),
        migrations.AddField(
            model_name='boletim',
            name='encerrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boletim',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('M', 'Matriculado'), ('T', 'Transferido'), ('RM', 'Reprovado por média'), ('RF', 'Reprovado por falta')], default='M', max_length=20),
        ),
    ]
