# Generated by Django 4.2.7 on 2024-01-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0011_rename_turma_aluno_turmas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
