# Generated by Django 4.2.7 on 2024-01-08 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0012_alter_media_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='turma',
            new_name='turmas',
        ),
    ]
