# Generated by Django 4.2.7 on 2024-02-10 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0012_alter_situacao_options_boletim_encerrar_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='frequencia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='boletim',
            name='frequencia',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='frequencia_boletim', to='pessoas.frequencia'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='ano',
        ),
    ]
