# Generated by Django 4.2.7 on 2024-02-10 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0013_alter_frequencia_unique_together_boletim_frequencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletim',
            name='frequencia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frequencia_boletim', to='pessoas.frequencia'),
        ),
    ]
