# Generated by Django 4.2.7 on 2024-02-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0014_alter_boletim_frequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletim',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('M', 'Matriculado'), ('T', 'Transferido'), ('RM', 'Reprovado por média'), ('RF', 'Reprovado por falta'), ('RFM', 'Reprovado por falta e por média')], default='M', max_length=30),
        ),
    ]
