# Generated by Django 4.2.7 on 2024-02-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0015_alter_boletim_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='escolas',
        ),
    ]
