# Generated by Django 4.2.7 on 2024-02-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0006_alter_aviso_diaagenda_alter_avisoescola_mural_and_more'),
        ('pessoas', '0017_remove_avaliacao_turma_boletim_turma'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boletim',
            unique_together={('ano', 'aluno', 'turma')},
        ),
    ]
