# Generated by Django 4.2.7 on 2024-02-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0018_alter_boletim_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='turmas',
        ),
    ]
