# Generated by Django 4.2.7 on 2024-02-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0006_alter_aviso_diaagenda_alter_avisoescola_mural_and_more'),
        ('pessoas', '0019_remove_aluno_turmas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boletim',
            unique_together={('aluno', 'turma')},
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='ano',
        ),
    ]
