# Generated by Django 4.2.7 on 2024-02-17 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0020_alter_boletim_unique_together_remove_boletim_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletim',
            name='frequencia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoas.frequencia'),
        ),
    ]
