# Generated by Django 4.2.7 on 2024-03-23 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0023_alter_frequencia_boletim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='boletim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boletim_frequencia', to='pessoas.boletim'),
        ),
    ]
