# Generated by Django 4.2.7 on 2024-03-23 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0024_alter_frequencia_boletim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recado',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='recado',
            name='boletim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boletim_recados', to='pessoas.boletim'),
        ),
    ]
