# Generated by Django 4.2.7 on 2024-03-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0025_remove_recado_pessoa_recado_boletim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recado',
            name='boletim',
        ),
        migrations.AddField(
            model_name='recado',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_recados', to='pessoas.pessoa'),
        ),
    ]
