# Generated by Django 4.2.7 on 2024-03-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0027_remove_agendarecados_aluno_agendarecados_boletim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendarecados',
            name='ano',
        ),
    ]
