# Generated by Django 4.2.7 on 2024-03-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0028_remove_agendarecados_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendarecados',
            name='boletim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boletim_agendas', to='pessoas.boletim'),
        ),
    ]
