# Generated by Django 4.2.7 on 2024-03-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0029_alter_agendarecados_boletim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporte',
            name='tipo',
            field=models.CharField(choices=[('C', 'CARRO'), ('O', 'ÔNIBUS'), ('V', 'VAN'), ('X', 'OUTROS')], default='x', max_length=20, verbose_name='tipo do veículo'),
            preserve_default=False,
        ),
    ]
