# Generated by Django 4.2.7 on 2024-03-31 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0030_alter_transporte_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporte',
            old_name='aluno',
            new_name='alunos',
        ),
    ]
