# Generated by Django 4.2.7 on 2024-04-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0031_rename_aluno_transporte_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletim',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='boletins_qr_codes/'),
        ),
        migrations.AddField(
            model_name='boletim',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
