# Generated by Django 4.2.7 on 2024-04-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0032_boletim_qr_code_boletim_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
