from .api.agenda_escolar_api_view import AgendaEscolarViewSet
from .api.aviso_api_view import AvisoViewSet
from .api.cardapio_api_view import CardapioMerendaViewSet
from .api.dia_agenda_api_view import DiaAgendaViewSet
from .api.disciplina_api_view import DisciplinaViewSet
from .api.email_escola_api_view import EmailEscolaViewSet
from .api.escola_api_view import EscolaViewSet
from .api.item_cardapio_api_view import ItemCardapioMerendaViewSet
from .api.sala_api_view import SalaViewSet
from .api.tarefa_api_view import TarefaViewSet
from .api.telefone_escola_api_view import TelefoneEscolaViewSet
from .api.turma_api_view import TurmaViewSet