# Generated by Django 4.2.7 on 2023-12-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'agendas escolares',
            },
        ),
        migrations.CreateModel(
            name='DiaAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_dias', to='escolas.agendaescolar')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('num_salas', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='escola_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCardapioMerenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'ítem do cardápio',
                'verbose_name_plural': 'ítens do cardápio',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('quantidade_alunos', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.BooleanField(default=False)),
                ('cadastrada_em', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.DateTimeField(blank=True, null=True)),
                ('diaAgenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia_tarefas', to='escolas.diaagenda', verbose_name='dia da agenda')),
            ],
        ),
        migrations.AddField(
            model_name='diaagenda',
            name='disciplina',
            field=models.ManyToManyField(blank=True, related_name='disciplinas_dias', to='escolas.disciplina'),
        ),
        migrations.CreateModel(
            name='CardapioMerenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaAgenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia_cardapios', to='escolas.diaagenda', verbose_name='dia da agenda')),
                ('item', models.ManyToManyField(blank=True, related_name='cardapios_itens', to='escolas.itemcardapiomerenda')),
            ],
            options={
                'verbose_name': 'cardápio da merenda',
                'verbose_name_plural': 'cardápios da merenda',
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('diaAgenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia_avisos', to='escolas.diaagenda', verbose_name='dia da agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=4)),
                ('turno', models.CharField(max_length=10)),
                ('agenda', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_turma', to='escolas.agendaescolar')),
                ('disciplina', models.ManyToManyField(blank=True, related_name='disciplinas_turmas', to='escolas.disciplina')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sala_turmas', to='escolas.sala')),
            ],
            options={
                'unique_together': {('nome', 'ano', 'turno')},
            },
        ),
        migrations.CreateModel(
            name='TelefoneEscola',
            fields=[
                ('telefone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='escolas.telefone')),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escola_telefones', to='escolas.escola')),
            ],
            options={
                'verbose_name': 'telefone',
            },
            bases=('escolas.telefone',),
        ),
        migrations.CreateModel(
            name='EmailEscola',
            fields=[
                ('email_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='escolas.email')),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escola_emails', to='escolas.escola')),
            ],
            options={
                'verbose_name': 'e-mail',
            },
            bases=('escolas.email',),
        ),
    ]
