# Generated by Django 4.2.7 on 2023-12-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='escola',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='escola_salas', to='escolas.escola'),
            preserve_default=False,
        ),
    ]
