# Generated by Django 4.2.7 on 2024-02-07 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avisoescola',
            options={'verbose_name': 'aviso da escola', 'verbose_name_plural': 'Avisos da escola'},
        ),
        migrations.AlterModelOptions(
            name='muralavisos',
            options={'verbose_name': 'mural de avisos', 'verbose_name_plural': 'Murais de avisos'},
        ),
        migrations.AddField(
            model_name='avisobase',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='diaagenda',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='diaagenda',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escola',
            name='quantidade_alunos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='atualizada_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardapiomerenda',
            name='turno',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=50),
        ),
        migrations.AlterField(
            model_name='escola',
            name='imagem',
            field=models.ImageField(blank=True, default='', null=True, upload_to='escolas_images/'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='num_salas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tipo',
            field=models.CharField(choices=[('E', 'Escola'), ('C', 'Casa')], max_length=10),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=10),
        ),
    ]
