# Generated by Django 4.2.7 on 2023-12-31 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendaescolar',
            options={'verbose_name': 'agenda escolar', 'verbose_name_plural': 'agendas escolares'},
        ),
        migrations.AlterModelOptions(
            name='diaagenda',
            options={'verbose_name': 'dia da agenda', 'verbose_name_plural': 'dias da agenda'},
        ),
        migrations.AddField(
            model_name='cardapiomerenda',
            name='data',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardapiomerenda',
            name='escola',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='escola_cardapios', to='escolas.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardapiomerenda',
            name='turno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='diaAgenda',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dia_avisos', to='escolas.diaagenda', verbose_name='dia da agenda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diaagenda',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_dias', to='escolas.agendaescolar'),
        ),
        migrations.AlterField(
            model_name='diaagenda',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emailescola',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escola_emails', to='escolas.escola'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='diaAgenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dia_tarefas', to='escolas.diaagenda', verbose_name='dia da agenda'),
        ),
        migrations.AlterField(
            model_name='telefoneescola',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escola_telefones', to='escolas.escola'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala_turmas', to='escolas.sala'),
        ),
        migrations.AlterUniqueTogether(
            name='cardapiomerenda',
            unique_together={('data', 'turno')},
        ),
        migrations.AlterUniqueTogether(
            name='diaagenda',
            unique_together={('data', 'agenda')},
        ),
        migrations.RemoveField(
            model_name='cardapiomerenda',
            name='diaAgenda',
        ),
    ]
