# Generated by Django 4.2.7 on 2024-05-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardapiomerenda',
            unique_together={('data', 'turno', 'escola')},
        ),
    ]
