# Generated by Django 4.2.7 on 2023-12-18 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='diaAgenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia_avisos', to='escolas.diaagenda', verbose_name='dia da agenda'),
        ),
        migrations.AlterField(
            model_name='cardapiomerenda',
            name='diaAgenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia_cardapios', to='escolas.diaagenda', verbose_name='dia da agenda'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='diaAgenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia_tarefas', to='escolas.diaagenda', verbose_name='dia da agenda'),
        ),
    ]
