# Generated by Django 4.2.7 on 2023-11-25 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='email',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='telefone',
        ),
        migrations.AddField(
            model_name='email',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escolas.escola'),
        ),
        migrations.AddField(
            model_name='telefone',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escolas.escola'),
        ),
    ]
