# Generated by Django 4.2.7 on 2023-11-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_remove_escola_email_remove_escola_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='cnpj',
            field=models.CharField(default='', max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escola',
            name='num_salas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
