# Generated by Django 4.2.7 on 2023-12-18 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_alter_aviso_diaagenda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='escola',
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='escola',
        ),
        migrations.CreateModel(
            name='TelefoneEscola',
            fields=[
                ('telefone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='escolas.telefone')),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escola_telefones', to='escolas.escola')),
            ],
            options={
                'verbose_name': 'telefone',
            },
            bases=('escolas.telefone',),
        ),
        migrations.CreateModel(
            name='EmailEscola',
            fields=[
                ('email_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='escolas.email')),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escola_emails', to='escolas.escola')),
            ],
            options={
                'verbose_name': 'e-mail',
            },
            bases=('escolas.email',),
        ),
    ]
