# Generated by Django 4.2.7 on 2023-11-26 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_escola_cnpj_escola_num_salas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='escolas.escola'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='escolas.escola'),
        ),
    ]
