# Generated by Django 4.2.7 on 2024-02-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_itemcardapiomerenda_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='quantidade_alunos',
            field=models.IntegerField(default=0),
        ),
    ]
