# Generated by Django 4.2.7 on 2023-12-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_remove_turma_agenda_agendaescolar_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendaescolar',
            name='nome',
        ),
    ]
