# Generated by Django 4.2.7 on 2023-12-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_remove_email_escola_remove_telefone_escola_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcardapiomerenda',
            options={'verbose_name': 'ítem do cardápio', 'verbose_name_plural': 'ítens do cardápio'},
        ),
    ]
