# Generated by Django 4.2.7 on 2024-02-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0004_alter_sala_quantidade_alunos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='sala',
            unique_together={('numero', 'escola')},
        ),
    ]
