# Generated by Django 4.2.7 on 2024-02-10 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0005_alter_sala_numero_alter_sala_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='diaAgenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dia_avisos', to='escolas.diaagenda', verbose_name='dia da agenda'),
        ),
        migrations.AlterField(
            model_name='avisoescola',
            name='mural',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mural_avisos', to='escolas.muralavisos', verbose_name='mural de avisos'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escola_salas', to='escolas.escola'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='diaAgenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dia_tarefas', to='escolas.diaagenda', verbose_name='dia da agenda'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sala_turmas', to='escolas.sala'),
        ),
    ]
