# Generated by Django 4.2.7 on 2024-01-08 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0005_alter_cardapiomerenda_turno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='disciplina',
            new_name='disciplinas',
        ),
    ]
