# Generated by Django 4.2.7 on 2024-01-08 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0006_rename_disciplina_turma_disciplinas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardapiomerenda',
            old_name='item',
            new_name='itens',
        ),
        migrations.RenameField(
            model_name='diaagenda',
            old_name='disciplina',
            new_name='disciplinas',
        ),
    ]
