# Generated by Django 4.2.7 on 2024-01-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0007_rename_item_cardapiomerenda_itens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaescolar',
            name='dias_nao_uteis',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
