# Generated by Django 4.2.7 on 2024-04-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0007_alter_muralavisos_ano_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('nome', 'ano', 'turno', 'sala')},
        ),
    ]
