# Generated by Django 4.2.7 on 2024-01-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0008_agendaescolar_dias_nao_uteis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaescolar',
            name='dias_nao_uteis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
