from .aluno_model import Aluno
from .avaliacao_model import Avaliacao
from .boletim_model import Boletim
from .dia_letivo_model import DiaLetivo
from .email_pessoa_model import EmailPessoa
from .frequencia_model import Frequencia
from .funcionario_model import Funcionario
from .pessoa_model import Pessoa
from .responsavel_model import Responsavel
from .telefone_pessoa_model import TelefonePessoa
from .telefone_transporte_model import TelefoneTransporte
from .transporte_model import Transporte
