from .aluno_serializer import AlunoSerializer
from .avaliacao_serializer import AvaliacaoSerializer
from .boletim_serializer import BoletimSerializer
from .dia_letivo_serializer import DiaLetivoSerializer
from .email_pessoa_serializer import EmailPessoaSerializer
from .frequencia_serializer import FrequenciaSerializer
from .funcionario_serializer import FuncionarioSerializer
from .media_serializer import MediaSerializer
from .responsavel_serializer import ResponsavelSerializer
from .telefone_pessoa_serializer import TelefonePessoaSerializer
from .telefone_transporte_serializer import TelefoneTransporteSerializer
from .transporte_serializer import TransporteSerializer
from .usuario_serializer import UsuarioSerializer, criar_usuario, atualizar_usuario
